version: "3.8"

services:
  browzie:
    build: .                # 👈 This tells Docker to build from your local Dockerfile
    image: browzie:latest   # 👈 Optional: name the image after building
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
